### ISSUE TITLE
How to load the trained model or checkpoints? 

### ISSUE THREAD

**Issue by Air000** [berenslab/t-simcne#13]
I have done the training, how can I load the .ckpt in lightning_logs/version_X/checkpoints/ ? So that I can re-plot the graph. I cannot find relevant API in document.

**Comment by jnboehm** [comment]
Hello, thank you for bringing this up.  At the time, we don't really implement the functionality directly.  So far I only trained it and then used the model in the same session that I only trained it in.

It should be possible however to load the PL model that is used under the hood and then call `tsimcne.transform()` afterwards.  Does that not work for you?

I agree that having the functionality to directly load the model would be preferable, but I haven't gotten around to implementing that yet unfortunately.

**Comment by Air000** [comment]
I tried to load the checkpoint with following code:
`model = PLtSimCNE.load_from_checkpoint(checkpoint_path="../checkpoint.ckpt", 
                                       strict=False,
                                       hparams_file='hparams.yaml')`

It raised the error:

`RuntimeError: Error(s) in loading state_dict for PLtSimCNE:
	size mismatch for model.projection_head.layers.2.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([128, 1024]).
	size mismatch for model.projection_head.layers.2.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([128]).`

I have no idea why the size of the layer mismatch.

**Comment by jnboehm** [comment]
Ah, the issue here is that we change the parameter during training, we have the parameters `out_dim` and `pretrain_out_dim`.  At first the output dimension is 128  (`pretrain_out_dim`) to get a good representation and then later on we change it to 2 (`out_dim`) so that we can get a 2D output for visualization.

I'm not exactly sure how to do that in the the snippet you provided (since `load_from_checkpoint` looks like a `classmethod`), but you'd have to change the parameter `pretrain_out_dim` to 2 so that the model is initialized with the correct shape as you are not training in your case, hence the model is never mutated to `out_dim` and you get the shape mismatch.

https://github.com/berenslab/t-simcne/blob/830bf0b9b6fa85af4e09ad6f1db05a52941aa962/tsimcne/tsimcne.py#L58-L63
