### ISSUE TITLE
data_transform in transform method of class TSimCNE is not being used.

### ISSUE THREAD

**Issue by KonstantinWilleke** [berenslab/t-simcne#6]
I'm sorry for the flurry of issues that I'm raising here, but I thought I'd just raise them as I go to replicate the code with my MEI data.

Here, the kwarg `data_transform` is unused. I understand that at this step, the data_transform are not needed by default, but I can see cases where it might be useful.

https://github.com/berenslab/t-simcne/blob/e8504e59d446ece10a7d5a4fba9e27551db342b9/tsimcne/tsimcne.py#L483

 I'd be happy to make a PR to change L487 to pass `self.data_transform_none if data_transform=None else data_transform`

And because this function is facing the user, it would benefit from a more extensive docstring.

**Comment by jnboehm** [comment]
The feedback is much appreciated!  I agree that the parameter should probably be better documented.  Is that something you would like to do?  Otherwise I'll write a docstring for it (and maybe think about whether it makes sense to also have an option to specify the test-time data transform at initialization time).
