### ISSUE TITLE
Bug: out_dim argument for PLtsimCNE model is not used per default.

### ISSUE THREAD

**Issue by KonstantinWilleke** [berenslab/t-simcne#7]
when instantiating a `ResNetFC` through the `make_model` function, the out_dim arg is not passed on.

See attached PR.

**Comment by KonstantinWilleke** [comment]
I encountered this bug when I tried to save the model in a quick-and-dirty way.
i.e. just save the state_dict of PLtSimCNE.model, and then re-build the model with the make_model fn and load the state dict.

Is there an easier or to use or more direct pytorch lightning functionality for saving/loading the PLtSimCNE or model instance?

**Comment by jnboehm** [comment]
Yeah, in the current case we don't want to use the `out_dim` initially since we first do some pretraining (so we first train in 128D, then change the model to map to `out_dim` instead).

I guess what would be a more principled solution would be to have a parameter along the lines of `initial_out_dim` or `pretrain_out_dim` that we would use instead of hardcoding 128.

**Comment by jnboehm** [comment]
As for saving the model, there is some functionality for saving and loading checkpoints.  https://lightning.ai/docs/pytorch/stable/common/checkpointing_basic.html

I just checked and the Trainer saves the model apparently, so you could load it from one of those checkpoints like so:
```python
model = PLtSimCNE.load_from_checkpoint("lightning_logs/version_103/checkpoints/epoch=999-step=59000.ckpt")
```

(code not tested.)
